light_sensor_task.c
MQ_LIGHTTASK_NAME
LUX_THRESHOLD
mqd_t lighttask_q
pthread_mutex_t stateChangeLock
volatile DAY_STATE_T isDay
DAY_STATE_T getLightTask_state()
Get the LightTask state object MT-safe.
DAY_STATE_T
Referenced by processRemoteRequest.
float getLightTask_lux()
Get the LightTask lux object. MT-safe as it calls a MT-safe function within.
float
Referenced by processRemoteRequest.
static void timer_handler_getAndUpdateState(union sigval sig)
mqd_t getHandle_LightTaskQueue()
Get the Handle LightTaskQueue object.
mqd_t
int light_task_queue_init()
int
Referenced by light_task_callback.
void light_task_processMsg()
int light_task_sensorUP(I2C_MASTER_HANDLE_T *i2c)
int light_task_sensorDOWN(I2C_MASTER_HANDLE_T *i2c)
void* light_task_callback(void *threadparam)
Entry point of the light task thread.
threadparam void*