apds9301_sensor.c
APDS9301_SENSOR_ID
int APDS9301_test()
int
Referenced by light_task_queue_init.
int APDS9301_write_ThLow(uint16_t thlow)
thlow int
int APDS9301_write_ThHigh(uint16_t thhigh)
thhigh int
int APDS9301_read_ThLow(uint16_t *thlow)
thlow int
int APDS9301_read_ThHigh(uint16_t *thhigh)
thhigh int
int APDS9301_readControlReg(uint8_t *ctrl_reg)
ctrl_reg int
int APDS9301_mode_highGain()
int
int APDS9301_mode_lowGain_default()
int
Referenced by APDS9301__setmode_allDefault.
int APDS9301_mode_interrupt(uint8_t enable)
enable int
int APDS9301_clearPendingInterrupt()
int
int APDS9301_mode_manualcontrol(uint8_t on)
on int
int APDS9301_mode_integrationTime(uint8_t x)
x int
int APDS9301_poweron()
int
Referenced by light_task_queue_init.
int APDS9301_powerdown()
int
Referenced by light_task_queue_init.
int APDS9301_readID(uint8_t *id)
id int
Referenced by APDS9301_test.
int APDS9301_readCh0(uint16_t *ch0_data)
ch0_data int
Referenced by APDS9301_getLux.
int APDS9301_readCh1(uint16_t *ch1_data)
ch1_data int
Referenced by APDS9301_getLux.
float APDS9301_getLux()
float
Referenced by getLightTask_lux.
uint8_t* APDS9301_memDump()
Gives a memdump of 15 len. IMP must free the address using return pointer.
uint8_t*
int APDS9301__setmode_allDefault()
Sets back the default configration of the sensor.
int