apds9301_sensor.h
APDS9301_SLAVE_ADDR
APDS9301_CMD_REG
APDS9301_CMD_WORD_EN
APDS9301_CMD_INT_CLEAR
APDS9301_CTRL_REG
APDS9301_TIMING_REG
APDS9301_ID_REG
APDS9301_INT_CTRL_REG
APDS9301_CH0_DATALOW
APDS9301_CH0_DATAHIGH
APDS9301_CH1_DATALOW
APDS9301_CH1_DATAHIGH
APDS9301_INT_TH_LL_REG
APDS9301_INT_TH_LH_REG
APDS9301_INT_TH_HL_REG
APDS9301_INT_TH_HH_REG
APDS9301_CTRL_POWERON
APDS9301_CTRL_POWEROFF
APDS9301_INTCTRL_IEN
APDS9301_TIMING_GAIN
APDS9301_TIMING_INTEG
APDS9301_TIMING_MANUAL
APDS9301_mode_interruptEnable
APDS9301_mode_interruptDisable_default
APDS9301_mode_integrationTime0
APDS9301_mode_integrationTime1
APDS9301_mode_integrationTime2_default
APDS9301_mode_integrationTime3
APDS9301_mode_manualcontrolON
APDS9301_mode_manualcontrolOFF_default
int APDS9301__setmode_allDefault()
Sets back the default configration of the sensor.
int
uint8_t* APDS9301_memDump()
Gives a memdump of 15 len. IMP must free the address using return pointer.
uint8_t*
int APDS9301_write_ThLow(uint16_t thlow)
thlow int
int APDS9301_write_ThHigh(uint16_t thhigh)
thhigh int
int APDS9301_read_ThLow(uint16_t *thlow)
thlow int
int APDS9301_read_ThHigh(uint16_t *thhigh)
thhigh int
int APDS9301_readControlReg(uint8_t *ctrl_reg)
ctrl_reg int
int APDS9301_mode_highGain()
int
int APDS9301_mode_lowGain_default()
int
Referenced by APDS9301__setmode_allDefault.
int APDS9301_mode_manualcontrol(uint8_t on)
on int
int APDS9301_mode_integrationTime(uint8_t x)
x int
int APDS9301_mode_interrupt(uint8_t enable)
enable int
int APDS9301_clearPendingInterrupt()
int
int APDS9301_poweron()
int
Referenced by light_task_queue_init.
int APDS9301_powerdown()
int
Referenced by light_task_queue_init.
int APDS9301_readID(uint8_t *id)
id int
Referenced by APDS9301_test.
int APDS9301_readCh0(uint16_t *ch0_data)
ch0_data int
Referenced by APDS9301_getLux.
int APDS9301_readCh1(uint16_t *ch1_data)
ch1_data int
Referenced by APDS9301_getLux.
float APDS9301_getLux()
float
Referenced by getLightTask_lux.
int APDS9301_test()
int
Referenced by light_task_queue_init.