common_helper.h
NUM_CHILD_THREADS
TASK_IDENTIFIER_T
volatile int aliveStatus[NUM_CHILD_THREADS][NUM_CHILD_THREADS]
pthread_mutex_t aliveState_lock
pthread_t pthread_id[NUM_CHILD_THREADS][NUM_CHILD_THREADS]
pthread_barrier_t tasks_barrier
const char* const task_identifier_string[NUM_CHILD_THREADS+1][NUM_CHILD_THREADS+1]
mqd_t get_queue_handle(TASK_IDENTIFIER_T taskid)
static const char* getTaskIdentfierString(TASK_IDENTIFIER_T taskid)
Get the Task Identfier String.
taskid const char*
int register_and_start_timer(timer_t *timer_id, uint32_t usec, uint8_t oneshot, void(*timer_handler)(union sigval), void *handlerArgs)
Registers a timer, addigns the handler and starts it.
timer_id usec oneshot timer_handler handlerArgs int
Referenced by light_task_callback, main_task_entry, temperature_task_callback.