my_i2c.h
BB_I2C_BUS_2
typedef struct i2c_handle I2C_MASTER_HANDLE_T
This is the handle for I2C mster and each master should have only one handle.
I2C_MASTER_HANDLE_T* getMasterI2C_handle()
Get the MasterI2C handle object.
I2C_MASTER_HANDLE_T *
void printErrorCode(int errorCode)
Prints the error code string to stdout.
errorCode
Referenced by light_task_queue_init, temperature_task_I2Cinit, temperature_task_I2Cdeinit.
int I2Cmaster_Init(I2C_MASTER_HANDLE_T *handle)
Inits the I2C master handle There is an internal state of the context which is maintained which gets updated with every init call Internal context goes to NULL is error in init This context points to the new handle that is passed as the parameter.
handle int SUCCESS=0 and ERROR =-1
Referenced by light_task_queue_init, temperature_task_I2Cinit.
int I2Cmaster_Destroy(I2C_MASTER_HANDLE_T *handle)
handle int
Referenced by light_task_queue_init, temperature_task_I2Cdeinit.
int I2Cmaster_read_byte(uint8_t slave_addr, uint8_t reg_addr, uint8_t *data)
slave_addr reg_addr data int
Referenced by APDS9301_readControlReg, APDS9301_mode_highGain, APDS9301_mode_lowGain_default, APDS9301_mode_interrupt, APDS9301_mode_manualcontrol, APDS9301_mode_integrationTime, APDS9301_readID, APDS9301_readCh0, APDS9301_readCh1, APDS9301_memDump.
int I2Cmaster_read_bytes(uint8_t slave_addr, uint8_t reg_addr, uint8_t *data, size_t len)
slave_addr reg_addr data len int
Referenced by APDS9301_read_ThLow, APDS9301_read_ThHigh, TMP102_setMode_SD_PowerSaving, TMP102_setMode_SD_Continuous_default, TMP102_setMode_TM_ComparatorMode_default, TMP102_setMode_TM_InterruptMode, TMP102_setMode_ALERT_ActiveLow_default, TMP102_setMode_ALERT_ActiveHigh, TMP102_setMode_EM_NormalMode_default, TMP102_setMode_EM_ExtendedMode, TMP102_setMode_CR_250mHZ, TMP102_setMode_CR_1HZ, TMP102_setMode_CR_4HZ_default, TMP102_setMode_CR_8HZ, TMP102_readMode_ALERT, TMP102_write_Tlow, TMP102_write_Thigh, TMP102_read_Tlow, TMP102_read_Thigh, TMP102_getTemp, TMP102_memDump.
int I2Cmaster_write(uint8_t slave_addr, uint8_t reg_addr)
Writes a byte/pointer register to the slave.
slave_addr reg_addr int
Referenced by APDS9301_clearPendingInterrupt.
int I2Cmaster_write_byte(uint8_t slave_addr, uint8_t reg_addr, uint8_t data)
slave_addr reg_addr data int
Referenced by APDS9301_mode_highGain, APDS9301_mode_lowGain_default, APDS9301_mode_interrupt, APDS9301_mode_manualcontrol, APDS9301_mode_integrationTime, APDS9301_poweron, APDS9301_powerdown.
int I2Cmaster_write_bytes(uint8_t slave_addr, uint8_t reg_addr, uint8_t *data, size_t len)
slave_addr reg_addr data len int
int I2Cmaster_write_word(uint8_t slave_addr, uint8_t reg_addr, uint16_t data, uint8_t lsb_first)
slave_addr reg_addr data lsb_first int
Referenced by APDS9301_write_ThLow, APDS9301_write_ThHigh, TMP102_setmode_allDefault, TMP102_setMode_SD_PowerSaving, TMP102_setMode_SD_Continuous_default, TMP102_setMode_TM_ComparatorMode_default, TMP102_setMode_TM_InterruptMode, TMP102_setMode_ALERT_ActiveLow_default, TMP102_setMode_ALERT_ActiveHigh, TMP102_setMode_EM_NormalMode_default, TMP102_setMode_EM_ExtendedMode, TMP102_setMode_CR_250mHZ, TMP102_setMode_CR_1HZ, TMP102_setMode_CR_4HZ_default, TMP102_setMode_CR_8HZ, TMP102_write_Tlow, TMP102_write_Thigh.