posixTimer.h
MICROSEC
int register_timer(timer_t *timer_id, void(*timer_handler)(union sigval), void *handlerArgs)
REgsiter the timer handler.
timer_id timer_handler handlerArgs int
Referenced by register_and_start_timer.
int start_timer(timer_t timer_id, uint64_t time_usec, uint8_t oneshot)
Starts the timer.
timer_id time_usec oneshot int
Referenced by register_and_start_timer.
int stop_timer(timer_t timer_id)
Stops the timer.
timer_id int
Referenced by main_task_entry.
int delete_timer(timer_t timer_id)
Destroys the timer.
timer_id int
Referenced by light_task_callback, main_task_entry, temperature_task_callback.