readConfiguration.c
CONFIG_DATA_NUM
CONFIG_FILE
CONFIG_DATA_INDEX
void* configurationData[CONFIG_DATA_NUM][CONFIG_DATA_NUM]
char* configdata_getLogpath()
char*
Referenced by logger_task_callback, configdata_flush.
uint32_t configdata_getSetupTime()
uint32_t
Referenced by configdata_flush.
uint32_t configdata_getAliveTimeout()
uint32_t
Referenced by configdata_flush.
int configdata_setup()
Should be called in the main task at the beginning.
int
Referenced by main_task_entry, configdata_flush.
void configdata_flush()
Should be called at teh end of main task. If not called, memory leak will occur.
Referenced by main_task_entry, configdata_flush.