temperature_sensor_task.c
MQ_TEMPERATURETASK_NAME
mqd_t temperaturetask_q
pthread_mutex_t tempChangeLock
volatile float latest_temperature
float getTempTask_temperature()
Get the TempTask temperature object MT-safe.
float
Referenced by processRemoteRequest.
static void timer_handler_getAndUpdateTemperature(union sigval sig)
mqd_t getHandle_TemperatureTaskQueue()
Get the Handle TemperatureTaskQueue object.
mqd_t
int temperature_task_queue_init()
int
Referenced by temperature_task_callback.
void temperature_task_processMsg()
int temperature_task_I2Cinit(I2C_MASTER_HANDLE_T *i2c)
i2c int
Referenced by temperature_task_callback.
int temperature_task_I2Cdeinit(I2C_MASTER_HANDLE_T *i2c)
i2c int
Referenced by temperature_task_callback.
void* temperature_task_callback(void *threadparam)
Entry point of the temp task thread.
threadparam void*