tmp102_sensor.c
const TMP102_CONFIG_REG_SETTINGS_T TMP102_CONFIG_DEFAULT
temp unit int
int TMP102_setmode_allDefault()
Brings back to default.
int
int TMP102_setMode(TMP102_CONFIG_REG_SETTINGS_T config)
int TMP102_setMode_SD_PowerSaving()
int
int TMP102_setMode_SD_Continuous_default()
int
Referenced by TMP102_setmode_allDefault.
int TMP102_setMode_TM_ComparatorMode_default()
int
Referenced by TMP102_setmode_allDefault.
int TMP102_setMode_TM_InterruptMode()
int
int TMP102_setMode_ALERT_ActiveLow_default()
int
Referenced by TMP102_setmode_allDefault.
int TMP102_setMode_ALERT_ActiveHigh()
int
int TMP102_setMode_EM_NormalMode_default()
int
Referenced by TMP102_setmode_allDefault.
int TMP102_setMode_EM_ExtendedMode()
int
int TMP102_setMode_CR_250mHZ()
int
int TMP102_setMode_CR_1HZ()
int
int TMP102_setMode_CR_4HZ_default()
int
Referenced by TMP102_setmode_allDefault.
int TMP102_setMode_CR_8HZ()
int
int TMP102_readMode_ALERT(uint8_t *al_bit)
al_bit int
int TMP102_write_Tlow(float tlow_C)
tlow_C int
int TMP102_write_Thigh(float thigh_C)
thigh_C int
int TMP102_read_Tlow(float *tlow_C)
tlow_C int
int TMP102_read_Thigh(float *thigh_C)
thigh_C int
int TMP102_getTemp(float *temp, TEMPERATURE_UNIT_T unit)
Gets the temperature value.
temp unit int
uint16_t* TMP102_memDump()
Gives a memdump of 4 len. IMP must free the address using return pointer.
uint8_t*